{
    "name":"Youtubetomp3.eu",
    "description": "Youtubetomp3.eu the fastest web app to download Youtube videos for free. Easily Convert youtube videos to mp3 and mp4 and save them to your PC, Mobile, and tablets.",
    "site_url":"http://localhost:3000",
    "theme_color":"#ffffff",
    "background_color":"#ffffff",
    "display":"standalone",
    "start_url":"/?utm_source=pwa",
    "icons":[
        {
            "src":"/assets/icons/icon-72x72.png",
            "sizes":"72x72",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/icon-96x96.png",
            "sizes":"96x96",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/icon-128x128.png",
            "sizes":"128x128",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/icon-144x144.png",
            "sizes":"144x144",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/icon-152x152.png",
            "sizes":"152x152",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/icon-192x192.png",
            "sizes":"192x192",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/icon-384x384.png",
            "sizes":"384x384",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/icon-512x512.png",
            "sizes":"512x512",
            "type":"image/png"
        }
    ],
    "screenshots":[
        {
            "src":"/assets/icons/image1.png",
            "sizes":"1080x2400",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/image2.png",
            "sizes":"1080x2400",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/image3.png",
            "sizes":"1080x2400",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/image4.png",
            "sizes":"1080x2400",
            "type":"image/png"
        },
        {
            "src":"/assets/icons/image5.png",
            "sizes":"1080x2400",
            "type":"image/png"
        }
    ]
}